### PR TITLE
v2 

### LINKED ISSUE #57: New Design
full-2

### PR DESCRIPTION
**Pull request by orta**
Uses [MuralJS](https://github.com/muraljs/mural) - fixes #57 #66 

- [x] Blocked by adding in artsy admin auth
- [x] Looks mostly like https://github.com/artsy/team-navigator/issues/57

### CODE REVIEW

**Comment by damassi** [comment]
Really awesome work on the new framework @craigspaeth 👏 

Only comment (and I'm even not sure if this is possible with the current setup) is that we should try to avoid relative import paths `../../../foo` which are brittle and something of a long-standing-yet-largely-ignored anti-pattern in the node community and instead setup something like https://github.com/tleunen/babel-plugin-module-resolver. I know Atom provides IDE support for this, and I imagine someone has built something for VSCode? By setting up https://www.npmjs.com/package/babel-node at the root of the project (along with a .babelrc) you should be able to enable proper paths (and use ES6+) all the way thorough the pipeline as well as support isomorphism out of the box.

**Comment by craigspaeth** [comment]
Thanks @damassi! I totally agree—some developer experience things the Node community fights against baffle me like relative imports and hot reloading. FWIW I did try to encourage changing NODE_PATH to aknowledge the [lib folder](https://github.com/muraljs/mural/blob/master/lib/new.js#L56) as a first-class citizen like node_modules, but I'd support going further than that too.

**Comment by damassi** [comment]
It's surprising how few know about this magical `NODE_PATH` variable!

**Comment by orta** [comment]
Fixes #29 #42 #47 #63 #57 #11

**Comment by orta** [comment]
Fixes #54 #53

**Pull request merged**
